version: '3.8'

services:
  db-flowers:
    image: postgres:15
    container_name: postgres_local
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: nestjs